-- Migration: initial schema
-- Better Auth core tables (generated by `pnpm exec auth generate`, better-auth 1.6.27)

CREATE TABLE "user" (
	"id" text NOT NULL PRIMARY KEY,
	"name" text NOT NULL,
	"email" text NOT NULL UNIQUE,
	"emailVerified" integer NOT NULL,
	"image" text,
	"createdAt" date NOT NULL,
	"updatedAt" date NOT NULL
);

CREATE TABLE "session" (
	"id" text NOT NULL PRIMARY KEY,
	"expiresAt" date NOT NULL,
	"token" text NOT NULL UNIQUE,
	"createdAt" date NOT NULL,
	"updatedAt" date NOT NULL,
	"ipAddress" text,
	"userAgent" text,
	"userId" text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE INDEX "session_userId_idx" ON "session" ("userId");

CREATE TABLE "account" (
	"id" text NOT NULL PRIMARY KEY,
	"accountId" text NOT NULL,
	"providerId" text NOT NULL,
	"userId" text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" date,
	"refreshTokenExpiresAt" date,
	"scope" text,
	"password" text,
	"createdAt" date NOT NULL,
	"updatedAt" date NOT NULL
);

CREATE INDEX "account_userId_idx" ON "account" ("userId");

CREATE TABLE "verification" (
	"id" text NOT NULL PRIMARY KEY,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expiresAt" date NOT NULL,
	"createdAt" date NOT NULL,
	"updatedAt" date NOT NULL
);

CREATE INDEX "verification_identifier_idx" ON "verification" ("identifier");

-- Bookmarks: a user's saved relationship to one media item.
-- See CONTEXT.md for the domain language (Bookmark, Status, Rating, Note).

CREATE TABLE "bookmarks" (
	"id" text NOT NULL PRIMARY KEY,
	"userId" text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
	"mediaType" text NOT NULL CHECK ("mediaType" IN ('movie', 'series', 'episode')),
	"mediaId" integer NOT NULL,
	"seriesId" integer,
	"seasonNumber" integer,
	"episodeNumber" integer,
	"status" text NOT NULL DEFAULT 'watchlist' CHECK ("status" IN ('watchlist', 'watching', 'completed', 'dropped')),
	"favorite" integer NOT NULL DEFAULT 0,
	"rating" real CHECK ("rating" >= 0 AND "rating" <= 5),
	"note" text,
	"createdAt" date NOT NULL,
	"updatedAt" date NOT NULL,
	UNIQUE ("userId", "mediaType", "mediaId")
);

CREATE INDEX "bookmarks_userId_idx" ON "bookmarks" ("userId");
CREATE INDEX "bookmarks_user_status_idx" ON "bookmarks" ("userId", "status");
